version: '3'

volumes:
  tmp_postgres_db_data:

services:
  lamassu-db:
    build: .
    container_name: lamassu-cloud-proxy-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - tmp_postgres_db_data:/var/lib/postgresql/data
    ports:
      - 5434:5432
